### ISSUE TITLE
Use ember-simple-auth?

### ISSUE THREAD

**Issue by Windvis** [patocallaghan/ember-octane-realworld#36]
Wouldn't most "real world" ember applications use ember-simple-auth? Maybe I'm biased since I've used it in every project I worked on 😄

**Comment by patocallaghan** [comment]
@Windvis That's fair. When I was initially spiking this app out I thought ember-simple-auth was a bit heavy and there wasn't a great story for ember-simple-auth + Octane/ES6 classes. Has that experience improved do you know?

**Comment by Windvis** [comment]
Nope it's still mixin galore 🤔. https://github.com/simplabs/ember-simple-auth/issues/1619 

Nevertheless I think that the realworld app should demonstrate how most Ember apps are made, right? And I assume that's with ember-simple-auth, even though it isn't pretty 😄.

**Comment by patocallaghan** [comment]
Yep, the plan was that the RealWorld app was to show how to build an idiomatic Ember app.

I was the one who removed ember-simple-auth from [Ember RealWorld](https://github.com/gothinkster/ember-realworld/pull/40) in the first place as I thought it complicated things 😬At the time I discussed it with @mansona and @Alonski and they agreed. I wonder if their opinions still hold? Should we use ember-simple-auth here instead? I'll be honest I'm not entirely enthused on having to use the mixin API though 😃

**Comment by patocallaghan** [comment]
@Windvis the code in this repo was merged back into Ember Realworld in https://github.com/gothinkster/ember-realworld/pull/99 so this repo will no longer be active. I see [Ember Simple Auth is close to implementing their new non-Mixin API](https://github.com/simplabs/ember-simple-auth/issues/2185). When that happens I think it might be a good opportunity to move to it then. Feel free to submit a PR (or open an issue to discuss) there when that happens if you'd like.
